### ISSUE TITLE
No module named pypd

### ISSUE THREAD

**Issue by jpzk** [quintoandar/airflow-pagerduty-plugin#2]
Even though I have pypd installed using pip with Python2.7 and Python3 and get this as a notification in my airflow web UI:

Broken plugin: [/Users/user/airflow/plugins/pagerduty_plugin.py] No module named 'pypd' 

Can you please help me, don't know why it cannot find the pypd dependency.

**Comment by ankitchiplunkar** [comment]
This is an important issue, we are not able to integrate this plugin using `$AIRFLOW_ENV/plugins` path

**Comment by jpzk** [comment]
Solved it

**Comment by sulabhtembhurkar** [comment]
> Solved it

How?

**Comment by sulabh4udacity** [comment]
> Solved it

how?
